name: teachmeiti
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  build_runner: ^2.5.4
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  firebase_storage: ^13.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
    - assets/fonts/
