// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZZSn0EzwAqzr5rQGRRmO2sFKCPlW9f0',
    appId: '1:916937890098:web:3b0473993dd37df53cdf2b',
    messagingSenderId: '916937890098',
    projectId: 'teachmeiti',
    authDomain: 'teachmeiti.firebaseapp.com',
    storageBucket: 'teachmeiti.firebasestorage.app',
    measurementId: 'G-ZGZ54VZ8BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0a7Qkr7xXPD-YYEDMaay90_hGruBKdV0',
    appId: '1:916937890098:android:72ba10d768d8cb0f3cdf2b',
    messagingSenderId: '916937890098',
    projectId: 'teachmeiti',
    storageBucket: 'teachmeiti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-DpFpltI7b96-F6IQWhg7eM3iShFkdo4',
    appId: '1:916937890098:ios:d944a2a444354f073cdf2b',
    messagingSenderId: '916937890098',
    projectId: 'teachmeiti',
    storageBucket: 'teachmeiti.firebasestorage.app',
    iosBundleId: 'com.example.teachmeiti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-DpFpltI7b96-F6IQWhg7eM3iShFkdo4',
    appId: '1:916937890098:ios:d944a2a444354f073cdf2b',
    messagingSenderId: '916937890098',
    projectId: 'teachmeiti',
    storageBucket: 'teachmeiti.firebasestorage.app',
    iosBundleId: 'com.example.teachmeiti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbZZSn0EzwAqzr5rQGRRmO2sFKCPlW9f0',
    appId: '1:916937890098:web:5207a8a7bb3ec50a3cdf2b',
    messagingSenderId: '916937890098',
    projectId: 'teachmeiti',
    authDomain: 'teachmeiti.firebaseapp.com',
    storageBucket: 'teachmeiti.firebasestorage.app',
    measurementId: 'G-VQYHCYG0DE',
  );
}
